### ISSUE TITLE
💡 [FEAT] Searching Filament behaviour

### ISSUE THREAD

**Issue by mharris1984** [MarksMakerSpace/filament-profiles#21]
First off, THANK YOU for making this!!!!  I've been using a big Excel spreadsheet I made with all the filimant info for my uses and tracking data.  To keep track of what I have on hand, how much I have on hand, and all the associated data for each spool of filament.  This site is fast, works great, and very well laid out!!!  

I have a few suggestions for features...  

1. When I search for a brand, i.e. Bambu Labs and click on a result, when I go back, the search is cleared out and I have to type in Bambu Labs again to get to my next color.  It would be nice if it stayed on my last search when I return.  Maybe just open results in a new tab so the main search doesnt reset? 
2. A way to track usage to keep an inventory... i.e. have a QR code that is seperate for each spool you have in stock on the label that you print off for infront of your spool on the shelf, or on a sticker on the spool, but when you scan it, brings you to a site that you can just put the ammount of filament that Bambu Studio or whatever slicer says you are using up.  So when you look at your inventory, you see on hand what filaments are running low. Maybe using the Bambu api to create a plugin on a browser or desktop or something that when you go to print, the AMS shows which RFID spool is being used and have it update the inventory.   
      a. Not sure how this can work, but my Home Assistant plug in is able to keep track of the spool, RFID, and such.  Since the AMS keeps track of how much filament is on the spool remaining, then if you create an AMS plugin that runs on your desktop, or somehow the site is able to connect to Bambu Cloud services, the AMS already keeps track and reports remaining filament on the spools.  So if I put down that I have 3 spools of white, and one of my spools is reporting in as 75% full, then display I have 2.25Kg of 
4. A reminder email that can be configurable for when to send it and set to recieve for after inventory on hand gets below xxkg.  

I wish I could help contribute to this project some.  This is something that I"ve been trying to figure out how to get up and running as a perminent setup and amazing layout and design so far!  I've been using old school Excel sheets until now and QR code generators to make my lables that way.  Really looking forward to what this site can deliver.  I dont know how I ran accross it, but amazing work!!!

**Comment by markcarroll** [comment]
Hi Mike, thanks for the words of encouragement, it really does help. I've spent a lot of time on this site so it is great to hear it is useful to people. 

First off, thank you for the suggestions.  I cannot improve the site without knowing how people are using it, so thank you for the feedback. Now for my responses...

1. The site should work as you described, and having just tested it again now, it does indeed do that for me.  Not sure why it is not working for you but I will keep an eye on it and see if I can track down inconsistencies. Also when you are on a detail page, you can click on the Bambu Lab name at the top and it will take you to a filtered list of just that brand - see the video [here](https://github.com/MarksMakerSpace/filament-profiles/issues/19#issuecomment-2496885742). 

2. I loved reading this one as I have very similar ideas for the [My Spools](https://3dfilamentprofiles.com/my/filaments) section. I  have also thought of using the MQTT Home Assistant plugin to track usage. I will definitely be adding more in this section. 

3. Great idea and a good follow on from #2. 

I am also thinking about a price tracking email so that you set up a price target and get an email when the filament price drops below that target. Would that be useful?

The site is written in TypeScript using NextJS, React and Supabase. That side of things I am quite happy with, but I may need help on the MQTT/HA side at some point. Also, more than anything else, just getting the word out would be most appreciated.  

Thanks again for your support and suggestions.

**Comment by mharris1984** [comment]
I tried the site on my laptop and it is wroking like it should now.  So must have been an issue with my other desktop chrome browser cache or something.   But it does work as it should, so this ticket can be closed.  

MQTT/HA integration would be awesome!  I am a heavy HA user and have been for years so my setup is pretty advanced.  Having my filiment inventory and tracking would be amazing.  I do have my Bambu Printer feeding to HA so it tracks the spool ammount left on each RFID tag.  I dont know if HA holds each info as I swap spools in and out or if the AMS system or Bambu servers know the ammount left on a spool from the RFID tag.  But it would be awesome to register each RFID to the spools color and show my real time(ish) usage.  I am not sure if Bambu Labs has an open API that can get that info, or if it is tracked/saved in HA when a spool is loaded and AMS registers that the RFID tag is in and says how much filament is left of the spool.  The filament tracking on the RFID tags is not perfect, but it is pretty close so I know when I need to put in a second spool during a print or purchase more. 

I'll have to checkout how to write in those other programs.  I'm now a bit older and used to only using Visual Studio to do all my programing and mostly in C#/.net/ASP/some PHP.  Now a days, the web programming has gone insane from when I learned HTML in 7th grade in 1997 and it had to be done all by hand, no IDE's. lol.

**Comment by mharris1984** [comment]
Also, until something is able to be designed and added to auto update, is there a way we can update partial spools on hand?  i.e. if I have 3 spools, to be able to set a spool ammount for each one.  default to 1k and have where i can update a column of three to update my stats when I print to keep track for now.  if thats a pain to add, then i understand.  Something like in the picture I drew up.  When I click the + sign to add a spool, it auto add's another spool # on the list in a column and a text box next to it with 1k auto filled as a new spool.  Because soemtimes I'll have multiple spools of the same color with some usagage or all full and one with only usage.  depends on the prints and scenerio. 
<img width="222" alt="Untitled" src="https://github.com/user-attachments/assets/893cdef2-13bd-4c6c-97e6-3418b2a39cfc">

**Comment by markcarroll** [comment]
@mharris1984 ooh thanks for the UI suggestion. I actually had the partial count in there at first but hadn't finalized the UI so I dialed it back so I could get a first release out.  I will see how I can work your suggestion into the UI. Now you've got me thinking about RFID serial numbers too. 

BTW had to laugh at your age comment. In 1997 I was working at Microsoft UK building web sites for big corporate clients so I've seen a lot of changes in that time too.
