### ISSUE TITLE
💡 [FEAT] Material Update - Polymaker Panchroma Matte PLA (Formerly Polyterra PLA)

### ISSUE THREAD

**Issue by ConnorJPSmith** [MarksMakerSpace/filament-profiles#24]
Suggest changing the following entry:

**Polyterra**

to:

**Panchroma Matte (Formerly Polyterra)**

Or something similar

**Comment by markcarroll** [comment]
I took a look at this and started adding the new names, but given how many there are and that they are all just the material types we already have, but with "Panchroma" in front of them, I am considering removing Panchroma again and giving the option of material and its type, without any brand names. Otherwise things may blow out of control.

**Comment by markcarroll** [comment]
I have added the new types
